name: Deploy client app to staging environment
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server(s)
      run: |
        mkdir -p ./tmpkeys && echo "${{ secrets.SSH_PRIVATE_KEY_STG }}" > ./tmpkeys/key.pem && chmod 600 ./tmpkeys/key.pem
        for HOST in ${{ vars.SSH_HOSTS_STG }}; do
          echo -e "\033[1mDeploying to $HOST\033[0m"
          ssh -o StrictHostKeyChecking=no -i ./tmpkeys/key.pem ${{ vars.SSH_USERNAME_STG }}@$HOST "/bin/bash /home/${{ vars.SSH_USERNAME_STG }}/bin/deploy"
        done
        rm ./tmpkeys/key.pem

